# Generated by Django 3.2.23 on 2023-11-08 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam_voetballer', models.CharField(max_length=100)),
                ('actuele_voetbalclub', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('datum_invoer', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_laatste_aanpassing', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
